### ISSUE TITLE
Activated service 'com.deepin.daemon.InputDevices' failed

### ISSUE THREAD

**Issue by thedrint** [linuxdeepin/dde-daemon#103]
Linked with this [issue](https://github.com/linuxdeepin/developer-center/issues/1139)
Don't know why but:
```
мая 03 20:10:44 pc dbus-daemon[5708]: [session uid=1000 pid=5708] Activating service name='com.deepin.daemon.InputDevices' requested by ':1.18' (uid=1000 pid=5885 comm="/usr/bin/dde-dock " label="unconfined")
мая 03 20:10:44 pc com.deepin.daemon.InputDevices[5708]: <warning> main.go:80: session manager does not allow me to run
мая 03 20:10:44 pc daemon/dde-session-daemon[5911]: main.go:80: session manager does not allow me to run
мая 03 20:10:44 pc dbus-daemon[5708]: [session uid=1000 pid=5708] Activated service 'com.deepin.daemon.InputDevices' failed: Process com.deepin.daemon.InputDevices exited with status 1
```

I reproduce this error on my Deepin 15.10 (updated from 15.9.3). Also try fresh install of 15.10 - same error.
But i cannot reproduce it in virtualbox  with same configurations.

**Comment by igorbarkowsky** [comment]
I found this error text in https://github.com/linuxdeepin/dde-daemon/blob/master/bin/dde-session-daemon/main.go#L80
Now i have no ideas why func allowRun() return false.

**Comment by electricface** [comment]
Because dde-session-daemon contains a lot of dbus services, if it is allowed to start, it will start many times dde-session-daemon, only one dde-session-daemon is allowed, and the rest should be quit as soon as possible.

**Comment by igorbarkowsky** [comment]
>  only one dde-session-daemon is allowed, and the rest should be quit as soon as possible.

@electricface But why does it affects InputDevices, but not other services (datetime or sound for example)?

And, what can i do with it? Which factors can influences this situation? Maybe some configs where i can delay start of dbus services or something else? Maybe you need some logs to inspect this situation?

I think it is important issue. Me, and some other users from russian deepin community, was reports about it on mydeepin.ru forum. I repeatly had it on 15.4, 15.5, 15.6 - on 15.8 all was fine).
I tried fresh install of 15.9 then update it to 15.10 (no install any soft) - got this error.
Tried fresh install of 15.10 (no install soft too) - got this error.

On VB i can't reproduce an error, but i had "session manager does not allow me to run" error for other services (fresh install of 15.9).

**Comment by felixonmars** [comment]
I believe logs from journal (e.g. the actual failure from previous dde-session-daemon) would help the investigation here.

**Comment by igorbarkowsky** [comment]
@felixonmars ok, there are logs from journalctl for two sessions (last and part of current) in attachment
[prev_boot.log](https://github.com/linuxdeepin/dde-daemon/files/3268525/prev_boot.log)
[current_boot.log](https://github.com/linuxdeepin/dde-daemon/files/3268526/current_boot.log)

In both files you can find these lines like:
```
Jun 08 15:23:40 pc com.deepin.daemon.InputDevices[8989]: <warning> main.go:80: session manager does not allow me to run
Jun 08 15:23:40 pc daemon/dde-session-daemon[9147]: main.go:80: session manager does not allow me to run
```

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
