### ISSUE TITLE
Exception in deamon network

### ISSUE THREAD

**Issue by Urgau** [linuxdeepin/dde-daemon#109]
<pre>[...] wpa_supplicant[587]: nl80211: deinit ifname=wlo1 disabled_11b_rates=0
[...] dhcpcd[539]: wlo1: new hardware address: 46:99:d1:23:26:21
[...] NetworkManager[520]: &lt;info&gt;  [1557917585.5198] device (wlo1): set-hw-addr: set MAC address to 46:99:D1:23:26:21 (scanning)
[...] NetworkManager[520]: &lt;info&gt;  [1557917585.6371] device (p2p-dev-wlo1): state change: unmanaged -&gt; unavailable (reason &apos;managed&apos;, sys-iface-state: &apos;managed&apos;)
[...] NetworkManager[520]: &lt;info&gt;  [1557917585.6399] bluez5: NAP: added interface 7C:76:35:D3:58:9B
[...] daemon/network[779]: state_handler.go:267: device disconnected, type wired, 20 =&gt; 10, reason[37] Le gestionnaire réseau s&apos;est mis en veille
[...] daemon/network[779]: state_handler.go:267: device disconnected, type wireless, 100 =&gt; 10, reason[37] Le gestionnaire réseau s&apos;est mis en veille
[...] dbus-daemon[730]: [session uid=1000 pid=730] Activating service name=&apos;org.freedesktop.Notifications&apos; requested by &apos;:1.15&apos; (uid=1000 pid=779 comm=&quot;/usr/lib/deepin-daemon/dde-session-daemon &quot;)
[...] daemon/network[779]: state_handler.go:267: device disconnected, type wired, 10 =&gt; 20, reason[2] Le périphérique est désormais géré
[...] aemon/network[779]: state_handler.go:267: device disconnected, type wireless, 10 =&gt; 20, reason[2] Le périphérique est désormais géré
[...] daemon/network[779]: <font color="#EF2929"><b>nm_custom_type.go:86: unknown device type 30</b></font>
                                               <font color="#EF2929"><b>  -&gt;  state_handler.go:267</b></font>
                                               <font color="#EF2929"><b>  -&gt;  auto.go:2696</b></font>
                                               <font color="#EF2929"><b>  -&gt;  signal.go:59</b></font>
                                               <font color="#EF2929"><b>  -&gt;  signal.go:41</b></font>
                                               <font color="#EF2929"><b>  -&gt;  asm_amd64.s:1337</b></font>
[...] daemon/network[779]: state_handler.go:267: device disconnected, type unknown, 10 =&gt; 20, reason[2] Le périphérique est désormais géré
[...] NetworkManager[520]: &lt;info&gt;  [1557917585.6958] sup-iface[0x560141a04430,wlo1]: supports 5 scan SSIDs
[...] NetworkManager[520]: &lt;info&gt;  [1557917585.6964] device (wlo1): supplicant interface state: starting -&gt; ready
[...] NetworkManager[520]: &lt;info&gt;  [1557917585.6964] device (p2p-dev-wlo1): state change: unavailable -&gt; disconnected (reason &apos;supplicant-available&apos;, sys-iface-state: &apos;managed&apos;)
[...] NetworkManager[520]: &lt;info&gt;  [1557917585.6967] device (wlo1): state change: unavailable -&gt; disconnected (reason &apos;supplicant-available&apos;, sys-iface-state: &apos;managed&apos;)
[...] daemon/network[779]: <font color="#EF2929"><b>nm_custom_type.go:86: unknown device type 30</b></font>
                                               <font color="#EF2929"><b>  -&gt;  state_handler.go:267</b></font>
                                               <font color="#EF2929"><b>  -&gt;  auto.go:2696</b></font>
                                               <font color="#EF2929"><b>  -&gt;  signal.go:59</b></font>
                                               <font color="#EF2929"><b>  -&gt;  signal.go:41</b></font>
                                               <font color="#EF2929"><b>  -&gt;  asm_amd64.s:1337</b></font>
[...] daemon/network[779]: state_handler.go:267: device disconnected, type unknown, 20 =&gt; 30, reason[42] Le supplicant 802.1X est maintenant disponible
[...] daemon/network[779]: state_handler.go:267: device disconnected, type wireless, 20 =&gt; 30, reason[42] Le supplicant 802.1X est maintenant disponible</pre>

**Comment by felixonmars** [comment]
This happens from time to time when NetworkManager has an update on its device types. This is a simple fix in case any one wants to get hands dirty.

**Comment by hermithuang** [comment]
it is because https://developer.gnome.org/NetworkManager/stable/nm-dbus-types.html define 30 types of network devices and nm_consts_gen.go only defines 26. the type 30 is NM_DEVICE_TYPE_WIFI_P2P, and you have a wifi card with p2p function

**Comment by BLumia** [comment]
Should be fixed in https://github.com/linuxdeepin/dde-daemon/pull/187 :)
