### ISSUE TITLE
dde-session-daemon print lots of `g_key_file_get_uint64` errors

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-daemon#12]
<a href="https://github.com/fasheng"><img src="https://avatars.githubusercontent.com/u/3049011?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @fasheng**
_Thursday Nov 26, 2015 at 02:45 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/116_

---

```
(dde-session-daemon:3851): GLib-CRITICAL **: g_key_file_get_uint64: assertion 'key_file != NULL' failed
```

**Comment by jouyouyun** [comment]
Fixed!
