### ISSUE TITLE
Slow Wifi / High ping when dde-session-daemon is running (Ubuntu 18.04)

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/dde-daemon#124]
SO i got this issue where my wifi is just very ban when the dde-session-daemon is running. Right now i just moved the binary  dde-session-daemon to /dde-temp/dde-session-deammon and it works fine (except that 50% of the features are not available). Pleas fix :C @electricface @BLumia @felixonmars @myml @justforlxz @snyh @zccrs

**Comment by felixonmars** [comment]
Some logs from dde-session-daemon may help here :)

**Comment by xhxm** [comment]
sorry for the late response, but which log do you mean / how can i get it??

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
