### ISSUE TITLE
Dock prints lots of "firefox overlap dock" errors under "Smart hide" mode

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-daemon#14]
<a href="https://github.com/fasheng"><img src="https://avatars.githubusercontent.com/u/3049011?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @fasheng**
_Thursday Nov 26, 2015 at 03:45 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/128_

---

```
com.deepin.daemon.Dock[5186]:  .:0: firefox overlap dock
```

**Comment by jouyouyun** [comment]
@electricface

**Comment by hualet** [comment]
Not reproducable any more.
