### ISSUE TITLE
dde-preload is a CPU hog

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-daemon#15]
<a href="https://github.com/felixonmars"><img src="https://avatars.githubusercontent.com/u/1006477?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @felixonmars**
_Thursday Nov 26, 2015 at 03:46 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/129_

----

dde-preload takes 100% CPU (one core) once or twice every minute, and lasts for 10~20s. This costs much battery.

**Comment by marianocarrazana** [comment]
Same here
