### ISSUE TITLE
dde-session-daemon  cpu占用一直 25

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-daemon#16]
<a href="https://github.com/zhuzilinuser"><img src="https://avatars.githubusercontent.com/u/12298476?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @zhuzilinuser**
_Monday Dec 07, 2015 at 12:19 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/151_

----

![img_20151207_201806](https://cloud.githubusercontent.com/assets/12298476/11626717/edebbd10-9d1f-11e5-817c-b937eff9480e.jpg)
![img_20151207_201810](https://cloud.githubusercontent.com/assets/12298476/11626718/ee1e5fc2-9d1f-11e5-9646-b0a3f1c67174.jpg)

然后控制中心启动特别卡，无法操作

**Comment by fasheng** [comment]
@zhuzilinuser 好像现在已经没有高CPU占用的问题了，你那里还有遇到吗？

**Comment by kirigayakazushin** [comment]
@fasheng  没有了。现在用着一切ok。
