### ISSUE TITLE
[网络/VPN] OpenConnect服务不可用

### ISSUE THREAD

**Issue by MidoriYakumo** [linuxdeepin/dde-daemon#168]
目前3.28.0+c1-2，配置并启用OpenConnect连接直接报“未提供VPN连接所需的密码”，貌似是认证对话框对应的服务在dbus上注册有问题
这个bug从大约15.9开始就一直没修复，希望尽快解决

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
