### ISSUE TITLE
dock failed to create desktop app info for steam (wine'd)

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-daemon#17]
<a href="https://github.com/felixonmars"><img src="https://avatars.githubusercontent.com/u/1006477?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @felixonmars**
_Wednesday Dec 09, 2015 at 06:38 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/161_

---

I get this message every a few seconds:

```
daemon/dock[4192]: .:0: create desktop app info for steam.exe.desktop(window id: 0x820000c) failed:
```

**Comment by jouyouyun** [comment]
@electricface

**Comment by electricface** [comment]
正常输出，现在应该没有了
