### ISSUE TITLE
xdg-open (via hotkeys) launches most recent handler, not default

### ISSUE THREAD

**Issue by drgeoffb** [linuxdeepin/dde-daemon#170]
When xdg-open is triggered via the Super-E hot key (default to launch file manager by way of 'inode/directory' mime type), the most recently added handler for the mime type is launched, NOT the default handler.

To reproduce (example):
1. install Visual Studio Code 1.39.2 via msft debian repo
2. This causes `/usr/share/applications/code.desktop` to be installed
3. `code.desktop` contains: `MimeType=text/plain;inode/directory;` See: [source](https://github.com/Microsoft/vscode/blob/fd08d32b40c8a9ff56777265bce3c385008c3cb1/resources/linux/code.desktop#L11)
4. Note that pressing `Super-E` hotkey now launches vscode, not dde-file-manager

Other info:
1. This issue (relating specifically to vscode) was dealt with as bugs [#41037](https://github.com/microsoft/vscode/issues/41037) and [#44344](https://github.com/microsoft/vscode/issues/44344) in microsoft/vscode and closed with the assessment that it's not a bug in vscode, it's due to 'misbehaving distros'. **Note: the discussion on these two bugs gives a good explanation of the apparent cause of the problem.**
2. This appears to be an unintended consequence of fixing dde-file-manager bug [#10](https://github.com/linuxdeepin/dde-file-manager/issues/10) 
3. This [thread](https://bbs.archlinux.org/viewtopic.php?id=223654) relating to DDE on ArchLinux offers additional useful information.

Workaround:
1. Issuing the command  
`xdg-mime default dde-file-manager.desktop inode/directory application/x-gnome-saved-search`  
overrides this behaviour by updating  
`~/.local/share/applications/mimeapps.list`
- Source: this [answer](https://stackoverflow.com/a/56120439) to this [stackoverflow question](https://stackoverflow.com/questions/44061584/linux-visual-studio-code-super-e).

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
