### ISSUE TITLE
Launching terminal app from launcher not working under archlinux

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-daemon#20]
<a href="https://github.com/oberon2007"><img src="https://avatars.githubusercontent.com/u/11800714?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @oberon2007**
_Tuesday Dec 22, 2015 at 23:46 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/199_

----

When I try to launch for example **htop** from the launcher, nothing happens.

**Comment by manateelazycat** [comment]
Launcher just support GUI applicaiton, please run those command in terminal.

**Comment by oberon2007** [comment]
I don't think this is satisfactory. People will see that launcher icon in the launcher for applications like htop and when they click it just nothing will happen.

**Comment by oberon2007** [comment]
installing gnome-terminal as a workaround works, but it's not a native deepin solution.
