### ISSUE TITLE
Wrong /etc/lsb_release parsing in parseInfoFile

### ISSUE THREAD

**Issue by Artoria2e5** [linuxdeepin/dde-daemon#21]
lsb_release 1.4 is a shell script to show the lsb_release info, and it sources (if you are not familiar with this, well, something like read-and-eval with a stack) the `/etc/lsb_release` file to get variable assignments.

Yes, it's a shell script, and you should use some shell-parsing techniques, e.g. using `Shlex.Split()` (there is a go version of this, right?).

In Python one may write something like:

``` Py
# Licensed under CC0-1.0 :)
# I will be happy if you give me some credit though:
# Mingye Wang <arthur2e5@aosc.io>
def shell_assignment_to_dict(sh=None):
    """
    Plug some lsb/os-release in to parse its variable assignments.

    This function is 100% good with os-release, but only 95% good with lsb-rel:

    * lsb-release is a shell-script without limits on its syntatical elements
      used. You may bump into commands or variable substitutions, which are
      explicitly disallowed in os-release. (LONG LIVE SYSTEMD!)
    * The only officaly good way to get lsb-release data is to run the command
      ``lsb_release``.

    It does do some error-checking: command tokens signaled by a token w/o '='
    will trigger an error in dict update, since there is only 1 element given.
    However, I am too lazy to check for bad varnames.

    Technical problems in shlex stops me from checking for variable-subst -- I
    cannot tell if the ``$`` happens in single quotes.
    """
    sh = '' if sh is None else sh
    return dict(map(lambda word: word.split('=', 1),
                    shlex.split(sh, comments=True)))

```

See AOSC-Dev/aosc-aaa#3 for something I posted about this. I caught this on felix's CR, but I guess nobody saw my comments. (BTW your CR site is so slow to load...)

Also, check out os-release (still a shell-compatible script, so Shlex again): https://www.freedesktop.org/software/systemd/man/os-release.html

**Comment by Arthur2e5** [comment]
Aside: the only "good" parsing officially is to invoke the command `lsb_release`, which is slow. If you feel bad about this, go for systemd os-release.

os-rel actually limits the shell syntax features used:

> It is possible to source the configuration from shell scripts, however, beyond mere variable assignments, no shell features are supported (this means variable expansion is explicitly not supported), allowing applications to read the file without implementing a shell compatible execution engine.

**Comment by jouyouyun** [comment]
@electricface

**Comment by electricface** [comment]
改成读取 lsb_release -a 命令的输出吗？

**Comment by jouyouyun** [comment]
Fixed!
