### ISSUE TITLE
Manjaro (Arch) i686: com.deepin.daemon.Accounts crashes during (auto)login

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-daemon#25]
![daemon accounts](https://cloud.githubusercontent.com/assets/11800714/17247049/804621f4-5590-11e6-8ad1-02579baa4bed.jpg)

**Comment by oberon2007** [comment]
This happens only when running 32bit.

**Comment by fasheng** [comment]
Thanks. Looks gir generator raise the panic... I will try to reproduce it later.

**Comment by fasheng** [comment]
@snyh This condition checking failed under i686 machine, any idea?
```"The Go gir world be damaged because interface{} implement changed. :(")```
https://github.com/linuxdeepin/go-gir-generator/blob/master/lib.in/gobject-2.0/holder.go#L34

**Comment by fasheng** [comment]
@felixonmars  OK, there a new tag **0.9.5** for go-gir-generator now, rebuilt the go pacakges will fix the issue.

**Comment by felixonmars** [comment]
All affected packages rebuilt in Arch.

**Comment by oberon2007** [comment]
Thank you! :+1:
