### ISSUE TITLE
Is systemd a hard dependency?

### ISSUE THREAD

**Issue by archfan** [linuxdeepin/dde-daemon#27]
Hi

I like this DE quite a lot and I am planning to port deepin desktop to other systems such as FreeBSD. 

Why is systemd listed as a dependency and what exactly depends on systemd? AFAIK Gnome 3 can be run without systemd with some extra work.

**Comment by fasheng** [comment]
Yes, looks only the `timedate` module use the systemd interface, you could disable it in dde-daemon and dde-control-center to make DDE run without systemd. You could have a try :)

**Comment by fasheng** [comment]
This will disable timedate module in dde-daemon
```gsettings set com.deepin.dde.daemon timedate false```

And comment this line will disable timedate module in dde-control-center
https://github.com/linuxdeepin/dde-control-center/blob/master/modules/modules.pro#L13

**Comment by fasheng** [comment]
Well, with the developers reminds, besides, we used the org.freedesktop.login1 DBus interface for dde-lock/dde-lockservice which seems implemented only by systemd. So this will be a trouble..

**Comment by archfan** [comment]
Thank you for your help. I appreciate it.

I did some preliminary testing on Arch Linux without systemd and it seems to work with few changes.  The only thing that I had to recompile without systemd-support was the package "gnome-session" which seemed to cause severe slowdown issues.

I found a couple of bugs while I was testing the latest version of Deepin on Arch Linux:

1) After running the Deepin File Manager some duplicate items appear on the desktop. These duplicates are dead. You can't remove them or rearrange them on the desktop. Only after rebooting they will disappear. A screenshot for better illustration is attached below.

![2016-08-23-204539_1038x773_scrot](https://cloud.githubusercontent.com/assets/9040936/17905282/a88126aa-6972-11e6-9e64-c0a0a29be54f.png)
2) When using the "efficient mode" taskbar, some tray icons disappear randomly. As seen below.
![2016-08-23-204559_297x81_scrot](https://cloud.githubusercontent.com/assets/9040936/17905285/abd16e0a-6972-11e6-9656-bbd1f9083e68.png)

**Comment by fasheng** [comment]
You could just report such issues to https://github.com/linuxdeepin/developer-center/issues, and our developers will see it through email or our internal chatting tool and report you quickly :)

1. For the repeated desktop icons issue, do you use nautilus or nemo file manager which will create a desktop window, too?

2. For the tray icon disappear issue, maybe we solved it in upstream @sbwtw

**Comment by archfan** [comment]
1. I'm only using the default Deepin File Manager. This issue also appears on a freshly installed and updated Deepin Linux 15.2 distribution. I've just tested it today.

2.  That would be great. :+1: It's still there on Deepin Linux 15.2 (and Arch) but if the next update cycle fixes it, I will report back.
.

**Comment by fasheng** [comment]
Thanks, got it.
@hualet

**Comment by archfan** [comment]
Just letting you now that the issue with the ghost desktop icons and the missing tray icons has been resolved recently. 

Thanks. I really enjoy using DDE.

**Comment by fasheng** [comment]
Thanks, enjoy it!
