### ISSUE TITLE
Dock daemon crashes repeatedly

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/dde-daemon#28]
Journal:
http://pastebin.ubuntu.com/23201504/

**Comment by hualet** [comment]
@electricface

**Comment by electricface** [comment]
https://github.com/BurntSushi/xgbutil/pull/35

**Comment by felixonmars** [comment]
It seems there's no crash now, but the dock daemon still exits and reloads without an error. I'm closing the issue for now and maybe re-open it when I have more info.
