### ISSUE TITLE
partial crash after using "startx /usr/bin/startdde"

### ISSUE THREAD

**Issue by sinatosk** [linuxdeepin/dde-daemon#32]
I'm not sure if this is the right repo to post this in

I don't use a display manager

I use arch linux 64bit with kernel 4.4.23-lts, NVIDIA Quadro K4000M drivers 370.28 and using pulseaudio for my audio

I have this weird problem... so I'll try to explain... it's sort of random

when I first do startx... it goes to the desktop. I see my wallpaper, busy mouse cursor, my dock launcher can open and close applications from the launcher,except launcher the icons look the same as if they haven't been initialised ( I use efficient mode on dock ), the control center won't load, can't logout, restart or shutdown, volume shows up when I click on it but then refuse to go away when I click away.

I switch to another tty and to kill deepin

If and only if I have 2 or more ( including the tty I use with deepin ) ttys ( text ) logged in while attempting to start deepin correctly... I see this error message ( only 2 parts of the error message that change is the process id and duration )

xxxx - process id

> daemon/loader[xxxx]: loader.go:156: enable module screenedge  failed: org.freedesktop.DBus.Error.Spawn.ChildExited:Process com.deepin.api.XMouseArea exited with status 2, cost 32.431398ms
>   ->  global.go:50
>   ->  daemon.go:114
>   ->  daemon.go:123
>   ->  main.go:83
>   ->  proc.go:183
>   ->  asm_amd64.s:2086

so I reboot my laptop and it still doesn't work and repeating the steps above leads to the same issue

this is the weird part

I start another desktop environment ( Budgie Desktop using "startx /usr/bin/budgie-desktop or Enlightenment using "startx /usr/bin/enlightenment_start" )... after that I logout out and do "startx /usr/bin/startdde" and sometimes... it works again and I don't see that error and presented earlier

heres another weird part

I can then repeatedly start and stop deepin numerous times until it randomly just decides to stop again but other times it doesn't... but if I reboot my laptop then it just doesn't work again along with that same error again.

I've tried deleting all of the cache and configs numerous times and none of that help... only if starting another desktop environment can I sometimes successfully startx on deepin

I know Go and C and looked through alot of the Go code but none of C and cannot find anything that gives out "status 2"

thanks

**Comment by manateelazycat** [comment]
@jouyouyun

**Comment by jouyouyun** [comment]
Recommended using dispaly manager to login, such as lightdm, direct startx may not be able to use DDE, this is a bug, the reason in the search.

**Comment by jouyouyun** [comment]
Write the line `exec dbus-launch startdde` to the file `~/.xinitrc`, then exec `startx` in tty, **not in fbterm**.

**Comment by jouyouyun** [comment]
Fixed!
