### ISSUE TITLE
[ VPN ] SNX Support ( SSL Network Extender from Checkpoint )

### ISSUE THREAD

**Issue by julianxhokaxhiu** [linuxdeepin/dde-daemon#37]
Hi,

I saw that you mostly support all the VPN connections but not SNX on your Desktop Environment.

Would you mind adding the support for it? The configuration is really easy ( see https://wiki.ubuntuusers.de/Check_Point_SSL_Network_Extender/#Erfolgreiche-Installation ).

I can support you for testing if needed. I am currently using Arch Linux.

Best regards,
Julian

**Comment by jouyouyun** [comment]
Hi:
We use NetworkManager as the backend, so need NetworkManager to support it.

**Comment by julianxhokaxhiu** [comment]
I see, unfortunately googling around it seems that the SNX support was dropped as it's a closed source solution. Too bad.

Then I'll close this as you cannot do very much :) But thanks anyway!
