### ISSUE TITLE
can one install dde on Kali linux ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/dde-daemon#42]
Hi,

Can one install dde on Kali Linux ?
If so the steps to the same is appreciated ...

thanks.

**Comment by jouyouyun** [comment]
@felixonmars

**Comment by felixonmars** [comment]
IIRC Kali is based on Debian. Our Debian upstream process is still in the early stage, only a few packages are live in the Debian repositories. So unfortunately it's not yet feasible for daily usage.

**Comment by yunusem** [comment]
You can use [Pardus](https://github.com/Pardus-Kurumsal?utf8=%E2%9C%93&q=dde&type=&language=) repositories, we have implemented DDE and made it to be able to run with all Debian derivatives (stretch +) 
Regards

**Comment by jouyouyun** [comment]
Great!
