### ISSUE TITLE
Daemon starts NetworkManager without asking user

### ISSUE THREAD

**Issue by shreyanshk** [linuxdeepin/dde-daemon#44]
Hi,
It seems to me that deepin-daemon will restart networkmanager without asking user even if it was stopped with "systemctl stop NetworkManager".
It doesn't seems ideal as there are cases where a user would want to stop networkmanager even with deepin desktop running. For example, while using airmon-ng or other utilities which require networkmanager to be turned off.
In other words, If the user wishes that network manager should be off, then it shouldn't work and deepin shouldn't enforce anything upon user. Default behaviour should be to warn user that network services are off.
Hope you feel the same.

OS: Arch Linux
Version: deepin-daemon 3.2.6-1

**Comment by jouyouyun** [comment]
Deepin network settings based on the NetworkManager, if disable NetworkManager, the dock and deepin control center will not work properly.
If you don't need the network settings, you can exec `gsettings set com.deepin.dde.daemon network false` to disable deepin network function, then reboot.
