### ISSUE TITLE
Add option to turn off grub2 configurator?

### ISSUE THREAD

**Issue by TylerBre** [linuxdeepin/dde-daemon#45]
For those of us who use custom configured bootloaders, dde-daemon can really mess stuff up as it resets /etc/default/grub every login. If it were possible to make this feature optional, or just be able to shut it off, that would be much appreciated. 

Thanks for all the great work!

**Comment by jouyouyun** [comment]
@electricface

**Comment by TylerBre** [comment]
@jouyouyun yes it does, I'm just interested in a way of turning off this feature. Currently I'm just manually deleting dde-daemon/grub2, which is not a good idea, and will just revert back on update.

Any insights are appreciated :)

**Comment by TylerBre** [comment]
Actually, I think if you just add in something like this, it would be better:

https://github.com/TylerBre/dde-daemon/compare/master...TylerBre-patch-1?quick_pull=1

Or optionally, allow users to set this value manually.

However, GRUB_GFXMODE depends on the resolution that your UEFI supports, not your monitor or GFX.

Just food for thought.

**Comment by felixonmars** [comment]
Alternatively, you can add that path to NoExtract field of pacman.conf so it won't be back once you deleted.

**Comment by jouyouyun** [comment]
If the file `/var/cache/deepin/grub2.log` exists and validity, the `daemon/grub2` don't modify `/etc/default/grub`. Has been tested in arch and deepin.

**Comment by TylerBre** [comment]
@felixonmars that's interesting for those of us on arch. Thanks for the tip

**Comment by DoveKi** [comment]
chattr +i /etc/defalut/grub

**Comment by jouyouyun** [comment]
Has fixed!

**Comment by TylerBre** [comment]
Thank you, @jouyouyun !
