### ISSUE TITLE
希望在连接了有线的情况下，减少无线的搜索频率

### ISSUE THREAD

**Issue by liu798675179** [linuxdeepin/dde-daemon#46]
版本:15.5
连接了有线，恰好这是有一个信号不怎么好的并可连接wifi出现在搜索范围，于是就看到右上角弹窗不停的连接，断开，再连接，再断开.....
看上去很心烦
既然都连接了有线，干嘛非要强求一定要连上无线……
此时只能关闭wifi才行……

**Comment by jouyouyun** [comment]
这个暂时只能靠用户来处理，要么关闭wifi，要么取消掉wifi的自动连接功能
