### ISSUE TITLE
Slow Wifi Connection in Arch linux after installing DDE

### ISSUE THREAD

**Issue by aadhilrf** [linuxdeepin/dde-daemon#47]
I have encountered slow wifi in Deepin OS 15 in my laptop with BCM4313 wifi adapter. I uninstalled deepin os and installed arch linux with gnome. Wifi was working fine in Arch linux until i installed dde. Installation of deepin DE made my wifi unusable. I am not the only on experiencing issues with BCM43* adapter. I guess the problem lies in the configuration of dde-daemon because, wifi worked fine when I just installed deepin applications on arch linux.
lspci output:

Network controller: Broadcom Limited BCM4313 802.11bgn Wireless Network Adapter (rev 01)
	Subsystem: Dell BCM4313 802.11bgn Wireless Network Adapter
	Kernel driver in use: bcma-pci-bridge
	Kernel modules: bcma

**Comment by jouyouyun** [comment]
Try move `/usr/lib/deepin-daemon/dde-session-daemon` to other directory, then try again.

**Comment by xhxm** [comment]
uhm so i have the same issue, i have a very high latency while playing games when the dde-session-daemon is running, killing it lowers the latency, but i cant controll the volume and other things dont work.
please fix the bug :(

**Comment by xhxm** [comment]
> Try move `/usr/lib/deepin-daemon/dde-session-daemon` to other directory, then try again.

As i said this helps but brings other problems with it.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
