### ISSUE TITLE
Wallpapers folder could have a maximum size

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/dde-daemon#48]
Every time you change wallpaper, a copy of it is stored in "~/Pictures/Wallpapers".

This creates some problems. For example when using an automatic wallpaper changer as [Variety](http://1.bp.blogspot.com/-JblJPLa-MoQ/UkaYW_3OZyI/AAAAAAAAEvs/EIRuWeAyEqY/s1000/variety-1.jpg), as seen in this [bug report](https://github.com/varietywalls/variety/issues/4).

The folder rapidly grows in size, and many [average users](https://wiki.ubuntu.com/One%20Hundred%20Papercuts/Average%20users) won't notice it. The only way to use such software is by manually deleting the wallpapers folder from time to time.

It would be nice if that folder had a maximum quota, so when it's exceeded the oldest wallpapers get deleted. Or even better not exist at all, probably if an user was really interested in keeping a wallpaper probably it would be better to manually save it.

Thanks for your attention.

**Comment by jouyouyun** [comment]
@electricface

**Comment by electricface** [comment]
I will change the code to not copy the wallpaper image file

**Comment by es20490446e** [comment]
Thank you.

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/33184/

I changed the wallpaper directory to ~/.config/deepin/dde-daemon/appearance/custom-wallpers.
Limit the number of files to 10, and after the limit is exceeded, the oldest file that is not the workspace wallpaper will be deleted.
