### ISSUE TITLE
Potential Abuse of Reusable Quote (%q) in bluetooth/utils_notify.go

### ISSUE THREAD

**Issue by Arthur2e5** [linuxdeepin/dde-daemon#5]
See https://github.com/linuxdeepin/dde-daemon/blob/release/3.0/bluetooth/utils_notify.go.

`%q` is not quite intended for use with UI text; actually 'a double-quoted string safely escaped *with Go syntax*' -- yes, a piece of reusable source code. For quoting normal people use a pair of curly single quotes `‘...’` in general UI text ([GNOME HIG](https://developer.gnome.org/hig/stable/typography.html.en#unicode), see also gettext `en@boldquot`), and for localization one might leave two strings consisting only of these characters to be left out for translation like `"‘"` and `"’"`.

CLI Dark Ages? People used `` `...' ``, and likewise they leave `` "`" `` and `"'"` out for translation.

**Comment by fasheng** [comment]
Thanks for the advice. So you mean we should use following string instead?
```go
format := Tr("Make sure '%q' is turned on and in range")
```

It's really an importante rule for translation, I will report to my colleagues to let them known.

**Comment by Arthur2e5** [comment]
%s. %q, as stated before, gives you a segment of string literal, and putting quotes around such literal sounds terrible.

> 你的设备 “"你好，世界"” 已经掉线

Nobody wants that, right? (Also assuming chinese is not being transformed into any `\u` crap here)

**Comment by Arthur2e5** [comment]
So here is how old things like `grep` handled their quoting to be translatable…

Basically, things are passed down to Gnulib: [Quoting](https://www.gnu.org/software/gnulib/manual/html_node/Quoting.html).

The full implementation is here at http://git.savannah.gnu.org/cgit/gnulib.git/tree/lib/quotearg.c#n1001. We only want the gettext-enabled `quote(char* s)` functionality, so let's just track it down…
- tailcall `quote_n(0, s)`
- tailcall `quote_n_mem(0, s, SIZE_MAX)`
- tailcall `quotearg_n_options(0, s, SIZE_MAX, {locale_quoting_style, 0, {0}, NULL, NULL})`
- newbuf.. on buf: `quotearg_buffer_restyled.....` (elide_outer_quotes = false)
  - (`case locale_quoting_style:` backslash escape enabled!)
  - ``strbuf = ngettext("`") + s + ngettext("'")``
  - (argsize is SIZE_MAX, we have a null-terminated string, so forget about `\0`..)
  - replace `\a` `\b` `\f` `\v` `\\` with their escaped forms..
  - `default:` some multibyte checks.
- ret buf.

These steps show what are needed by GNU guys to make their things. Hmm, now I feel like you should just write something that chops off the quotes from `%q` results and replace them with good quotes. I don't have Go here, but hopefully they will not `\u`-ize non-ascii things.

**Comment by fasheng** [comment]
Amazing skill!

Looks I misunderstand you at first. You mean we should quote the argument string through a general function to make the localization right. Yes, it's a better style, I have post it to the upstream developer center, and welcome to discuss more things there :)

BTW: looks the bluetooth module do not need a quoting operation for it should provide the original name of the device~

**Comment by snyh** [comment]
There has a g_shell_quote function we can use.
But it need invoke cgo which is too expensive.

**Comment by Arthur2e5** [comment]
Yes, and that's why I wrote down what it basically does [here](https://github.com/linuxdeepin/dde-daemon/issues/5#issuecomment-173091353) so you can just implement it yourself even without reading the code (and breaking some clean-room rules or whatever)…

**Comment by snyh** [comment]
The std packages of golang has this https://golang.org/pkg/strconv/#Quote
Thanks notice the quote problem

**Comment by Arthur2e5** [comment]
……The quote function is merely another `%q`:  a double-quoted Go string literal representing s.

However, as mentioned in that comment again, I think just removing the quotes from the string literal produced and plugging in the localized quotes is acceptable.
