### ISSUE TITLE
Screen brightness to be preserved after reboot

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/dde-daemon#52]
HOW TO REPRODUCE:
- Using the control center, lower the screen brightness.
- Reboot.

RESULT:
- After login the screen brightness is as set for a few seconds. But after a while it resets to maximum, even when in the control center the brightness bar isn't still at its maximum setting.

SYSTEM SPECS:
- Deepin desktop 15.6
- Linux kernel 4.4.54
- Xorg graphic server 1.19.6
- Dbus 1.12.8
- Manjaro operating system 17.1.11 stable branch

**Comment by es20490446e** [comment]
Disappeared for a while, but it reappeared. Here you have [things that I have tested](https://forum.manjaro.org/t/the-screen-brightness-isnt-preserved-between-reboots/68007).

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
