### ISSUE TITLE
[Arch] dde-sesion-daemon eats CPU

### ISSUE THREAD

**Issue by KawaiDesu** [linuxdeepin/dde-daemon#54]
Hello. I'm looking in DDE on Archlinux and noticed, that there are significant usage of CPU.
Looking at htop i think that dde-session-daemon very actively talks to NetworkManager daemon via dbus (see screenshot).
![screenshot_2018-09-10_12-34-16](https://user-images.githubusercontent.com/5793027/45291873-01d08080-b4fc-11e8-925f-eb029386104d.png)
If i disconnect from Wi-Fi network or entirely disable wireless network in native dde Wi-Fi menu, they are stop. Disabling network plugin does not help - if i connect via nm-applet problem still there.
Version         : 3.2.24.3-1
Build Date      : Fri 07 Sep 2018 12:26:15 MSK

Any suggestions?

**Comment by felixonmars** [comment]
Looks like NetworkManager and the system dbus are also using quite some CPU time, does dde-session-daemon query NetworkManager via dbus very frequently? @jouyouyun @electricface 

Also @KawaiDesu do you happen to have a lot of network interfaces, via something like docker?

**Comment by KawaiDesu** [comment]
Nope, just lo, lan and wifi (it's laptop).

**Comment by felixonmars** [comment]
I see, let's see if the developers have an idea.

**Comment by KawaiDesu** [comment]
Also, there is no such problem, when i'm on wired connection only (both - still problem). So the problem somewhere near wireless connections.

**Comment by KawaiDesu** [comment]
Any updates here?

**Comment by jouyouyun** [comment]
@KawaiDesu If bug occurred, please open terminal to exec `dbus-monitor "sender=com.deepin.daemon.Network" > /tmp/daemon_network.log 2>&1` , then open the other terminal to exec `sudo dbus-monitor --system "sender=org.freedesktop.NetworkManager" > /tmp/nm.log 2>&1`, wait for 5 minutes, then upload the files `/tmp/daemon_network.log` and `/tmp/nm.log`.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
