### ISSUE TITLE
【建议】四指左右滑动切换桌面改进建议

### ISSUE THREAD

**Issue by spencerwooo** [linuxdeepin/dde-daemon#55]
目前默认的滑动方式和我的理解有些出入：四指左滑向右切换桌面、右滑则向左。这个操作第一感觉有些反常。
我个人在 `/usr/share/dde-daemon/gesture.json` 下将两个操作的滑动方向进行了更改，这个方向感觉就很正常了，期待更新～
![deepinscreenshot_deepin-terminal_20181024112505](https://user-images.githubusercontent.com/32114380/47404341-852df480-d77f-11e8-907c-85572bcf1f09.png)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
