### ISSUE TITLE
manager.go:275: failed to new user object Invalid uid: 999

### ISSUE THREAD

**Issue by david-barbion** [linuxdeepin/dde-daemon#56]
dde-session-daemon continuously crashes with the error: `manager.go:275: failed to new user object Invalid uid: 999`.
This makes Deepin desktop totally unusable and sluggish.

Attached is the full trace of dde-session-daemon.
[dde-session-daemon.log](https://github.com/linuxdeepin/dde-daemon/files/2593094/dde-session-daemon.log)

**Comment by david-barbion** [comment]
I forgot to mention that this occurs since 3.7.0 (on Arch)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
