### ISSUE TITLE
[Arch] Deepin is laggin if no gesture.json file is present

### ISSUE THREAD

**Issue by mikield** [linuxdeepin/dde-daemon#59]
I have noticed a weird bug, if I will remove `/usr/share/dde-daemon/gesture.json` and reboot - deepin will lag (I think it tries to get this file, and eats a lot of CPU).

Is there an option to disable build in Deepin Gestures recognition?

**Comment by mikield** [comment]
@jouyouyun when this file is present but is empty - everything is OK.

**Comment by electricface** [comment]
I can't reproduce this problem.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
