### ISSUE TITLE
SSTP is not working

### ISSUE THREAD

**Issue by modaresimr** [linuxdeepin/dde-daemon#61]
Dear Deepin,
The new feature in deepin 15.9 "SSTP" is not working.
Thanks for this feature but please fix the problem
Thanks

**Comment by jouyouyun** [comment]
@electricface

**Comment by electricface** [comment]
Make sure the network-manager-sstp package is installed 
```
sudo apt install network-manager-sstp
```

**Comment by alim1369** [comment]
the result of this action is : 
`Unable to locate package network-manager-sstp`
It is a new feature in deepin 15.9 it should not depend on new package to install.
there is an option  to create a sstp vpn but after i created this it will not doing any thing

**Comment by alim1369** [comment]
@electricface 
the result of this action is :
`Unable to locate package network-manager-sstp`
It is a new feature in deepin 15.9 it should not depend on new package to install.
there is an option to create a sstp vpn but after i created this it will not doing any thing

**Comment by alim1369** [comment]
@electricface @jouyouyun no solution?

**Comment by felixonmars** [comment]
@zccrs Is this a problem with repositories?

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
